"""
Константы и статусы для домена матчинга Random Coffee.

Значения синхронизированы с требованиями из ТЗ.
"""

from __future__ import annotations

# Match statuses
MATCH_STATUS_PENDING_RESPONSE = "pending_response"
MATCH_STATUS_SKIPPED = "skipped"
MATCH_STATUS_WAITING_SLOTS = "waiting_slots"
MATCH_STATUS_WAITING_CONFIRM = "waiting_confirm"
MATCH_STATUS_SCHEDULED = "scheduled"
MATCH_STATUS_COMPLETED = "completed"
MATCH_STATUS_CANCELLED_BY_A = "cancelled_by_a"
MATCH_STATUS_CANCELLED_BY_B = "cancelled_by_b"
MATCH_STATUS_CANCELLED_ADMIN = "cancelled_admin"
MATCH_STATUS_USER_A_BLOCKED = "user_a_blocked"
MATCH_STATUS_USER_B_BLOCKED = "user_b_blocked"
MATCH_STATUS_EXPIRED_TIMEOUT = "expired_timeout"

MATCH_ACTIVE_STATUSES = {
    MATCH_STATUS_PENDING_RESPONSE,
    MATCH_STATUS_WAITING_SLOTS,
    MATCH_STATUS_WAITING_CONFIRM,
    MATCH_STATUS_SCHEDULED,
}

MATCH_INACTIVE_STATUSES = {
    MATCH_STATUS_COMPLETED,
    MATCH_STATUS_SKIPPED,
    MATCH_STATUS_CANCELLED_BY_A,
    MATCH_STATUS_CANCELLED_BY_B,
    MATCH_STATUS_CANCELLED_ADMIN,
    MATCH_STATUS_USER_A_BLOCKED,
    MATCH_STATUS_USER_B_BLOCKED,
    MATCH_STATUS_EXPIRED_TIMEOUT,
}

MATCH_USER_RESPONSE_NONE = "none"
MATCH_USER_RESPONSE_READY = "ready"
MATCH_USER_RESPONSE_SKIP = "skip"
MATCH_USER_RESPONSE_CONFIRM = "confirm"

MATCH_RESPONSE_VALUES = {
    MATCH_USER_RESPONSE_NONE,
    MATCH_USER_RESPONSE_READY,
    MATCH_USER_RESPONSE_SKIP,
    MATCH_USER_RESPONSE_CONFIRM,
}

# Fallback defaults (дублируют DEFAULT_SETTINGS, но в числовом виде)
DEFAULT_RESPONSE_TIMEOUT_HOURS = 8
DEFAULT_REMINDER_INTERVAL_HOURS = 2
DEFAULT_REPEAT_PAIR_COOLDOWN_WEEKS = 1
DEFAULT_MIN_JACCARD = 0.3

# Slot picking defaults
MATCH_SLOT_CALENDAR_DAYS = 14
MATCH_SLOT_TIME_WINDOWS = [
    ("09:00", "11:00"),
    ("11:00", "13:00"),
    ("13:00", "15:00"),
    ("15:00", "17:00"),
    ("17:00", "19:00"),
    ("19:00", "21:00"),
]

