"""
Константы и статусы для домена матчинга Random Coffee.

Значения синхронизированы с требованиями из ТЗ.
"""

from __future__ import annotations

# Match statuses
MATCH_STATUS_PENDING_RESPONSE = "pending_response"
MATCH_STATUS_SKIPPED = "skipped"
MATCH_STATUS_MATCHED = "matched"
MATCH_STATUS_COMPLETED = "completed"
MATCH_STATUS_CANCELLED_BY_A = "cancelled_by_a"
MATCH_STATUS_CANCELLED_BY_B = "cancelled_by_b"
MATCH_STATUS_CANCELLED_ADMIN = "cancelled_admin"
MATCH_STATUS_USER_A_BLOCKED = "user_a_blocked"
MATCH_STATUS_USER_B_BLOCKED = "user_b_blocked"
MATCH_STATUS_EXPIRED_TIMEOUT = "expired_timeout"

MATCH_ACTIVE_STATUSES = {
    MATCH_STATUS_PENDING_RESPONSE,
    MATCH_STATUS_MATCHED,
}

MATCH_INACTIVE_STATUSES = {
    MATCH_STATUS_COMPLETED,
    MATCH_STATUS_SKIPPED,
    MATCH_STATUS_CANCELLED_BY_A,
    MATCH_STATUS_CANCELLED_BY_B,
    MATCH_STATUS_CANCELLED_ADMIN,
    MATCH_STATUS_USER_A_BLOCKED,
    MATCH_STATUS_USER_B_BLOCKED,
    MATCH_STATUS_EXPIRED_TIMEOUT,
}

MATCH_USER_RESPONSE_SKIP = "skip"
MATCH_USER_RESPONSE_CONFIRM = "confirm"

MATCH_RESPONSE_VALUES = {
    MATCH_USER_RESPONSE_SKIP,
    MATCH_USER_RESPONSE_CONFIRM,
}

